### PR TITLE
fix: remove `isLastAuthor` validation

### LINKED ISSUE #21: last_author may be null in a story object
If we try to get this code working on a clean just created space, all works fine except for the fact thet get fetch stories call seems to return no results. This is unexpected since the default space contains one story with the name 'home'. After some debugging it became clear that this story does NOT have a `last_author`. So this line

https://github.com/storyblok/custom-app-examples/blob/4f669d7312913a94d864a71ff45886e9a9c4d386/app-nextjs-starter/src/Story.ts#L16C3-L16C17

will discard this as not correct therefore the `isStory` call also fails and the `isStories` call will also fail for all arrays that contain this default home story object.

This is confusing for a developer starting  with plugin dev.

Since all manually made stories do have a valid `last_author` field, the best solution would be to tp make the default space initialized with stories that gave some fake `last_author` with a `friendly_name` of e.g. "J. Doe" so this code will not break here. 

If it is more common to have stories without a `last_author` (e.g. after importing using the management API), it would be more appropriate to allow this code to work also on empty `last_author` fields.

### PR DESCRIPTION
**Pull request by demetriusfeijoo**
Ticket: EXT-1935
fixes #21

## What

Since for every newly created space, a default story is added automatically (home) and for this story, no `last_author` is provided, some adjustments were required to make it optional in our starter examples and does not break the page.

Screenshot 2023-08-25 at 08 38 27

Screenshot 2023-08-25 at 08 37 51

### CODE REVIEW

File: app-nextjs-starter/src/Story.ts [hunk 1]
```diff
@@ -30,8 +24,7 @@ export const isStory = (data: unknown): data is Story =>
   typeof data.slug === 'string' &&
   'updated_at' in data &&
   typeof data.updated_at === 'string' &&
-  'last_author' in data &&
-  isLastAuthor(data.last_author)
+  'last_author' in data
```
Comment (eunjae-lee) [inline app-nextjs-starter/src/Story.ts]: What's the default value of last_author here? Is it empty string or undefined? If undefined, this condition will fail, right?

**Review by eunjae-lee — CHANGES_REQUESTED** [review]
This PR looks overall. I've left one question, and also the CI is broken. Could you take a look?

File: app-nextjs-starter/src/Story.ts (hunk 1 above)
Comment (demetriusfeijoo) [reply app-nextjs-starter/src/Story.ts]: Hey @eunjae-lee, thanks for your question. 

The default value for `last_author` is `null`.

Screenshot 2023-08-25 at 14 23 48

**Comment by demetriusfeijoo** [comment]
@eunjae-lee, the CI broking was something related to the action itself, I guess... I just rerun it and worked 😅.

File: app-nextjs-starter/src/Story.ts (hunk 1 above)
Comment (eunjae-lee) [reply app-nextjs-starter/src/Story.ts]: ahh... it's `null`. I think this condition may give false impression that `last_author` exists in the data. What if we remove the condition at all?

Comment (demetriusfeijoo) [reply app-nextjs-starter/src/Story.ts]: I think the `last_author` property indeed exists inside the data, although it doesn't have any defined value. 

This condition validates the schema somehow so, I don't think it would be bad to have it.

However, as you felt this way, maybe others also feel the same, so I'm going to remove it. 😜

Comment (demetriusfeijoo) [reply app-nextjs-starter/src/Story.ts]: Validation removed @eunjae-lee.

**Comment by eunjae-lee** [comment]
I've updated the description to follow this format. Now, once this pull request gets merged, the linked issue will automatically be closed as well.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Review by eunjae-lee — APPROVED** [review]
looks good to me!

**Comment by demetriusfeijoo** [comment]
Thanks for the review and also linking the issue @eunjae-lee 🙌
